twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: '%site_name%'
        site_logo_url: '%site_logo_url%'
        survey_logo_url: '%survey_logo_url%'
        survey_logo_alt: '%survey_logo_alt%'
