easy_admin:
    entities:
        Survey:
            class: AppBundle\Entity\Survey
            list:
                actions:
                    - name: survey_show
                      type: route
                      label: Share
                    - show
                    - edit
                    - delete

                fields:
                    - property: title
                      # template: share.html.twig
                    - property: createdAt
                    - property: questions
                    - property: answers

            show:
                fields:
                    - property: title
                    - property: description
                    - property: configuration
                      template: configuration.html.twig
                    - property: questions
                    - property: answers
                      template: answers.html.twig

            form:
                fields:
                    - property: title
                    - property: description
                    - property: configuration
                      type: AppBundle\Form\Type\ConfigurationType
                    - property: questions
                      type: collection
                      type_options:
                        entry_type: AppBundle\Form\Type\QuestionType
                        by_reference: false
                        required: true
                      embedded: true

        Answer:
            class: AppBundle\Entity\Answer
