easy_admin:
    design:
        assets:
            css:
                - 'assets/easyadmin.css'

    entities:
        Survey:
            class: AppBundle\Entity\Survey
            list:
                actions:
                    - shareSurvey
                    - show
                    - edit
                    - delete

                fields:
                    - property: title
                      # template: share.html.twig
                    - property: description
                    - property: questions
                    - property: answers
                    - property: createdAt

            show:
                fields:
                    - property: title
                    - property: description
                    - property: configuration
                      template: configuration.html.twig
                    - property: questions
                    - property: answers
                      template: answers.html.twig

            form:
                fields:
                    - property: title
                    - property: description
                    - property: configuration
                      type: AppBundle\Form\Type\ConfigurationType
                    - property: questions
                      type: collection
                      type_options:
                        entry_type: AppBundle\Form\Type\QuestionType
                        by_reference: false
                        required: true
                      embedded: true

        Answer:
            class: AppBundle\Entity\Answer
            disabled_actions: [edit, delete]
            list:
                actions:
                    - name: answer_show
                      type: route
                      label: Show
                fields:
                    - property: title
                    - property: author
                    - property: description
                    - property: createdAt
