ivory_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar:
                -
                    name: "styles"
                    items: ['Format', 'Bold', 'Italic', 'BulletedList', 'Link']

easy_admin:
    site_name: '%site_name%'
    design:
        assets:
            css:
                - 'assets/dist/css/easyadmin.css'

    entities:
        Survey:
            class: AppBundle\Entity\Survey
            list:
                actions:
                    - shareSurvey
                    - show
                    - edit
                    - delete

                fields:
                    - property: title
                      # template: share.html.twig
                    - property: description
                    - property: questions
                    - property: answers
                      template: answers.html.twig
                    - property: createdAt

            show:
                fields:
                    - property: title
                    - property: answers
                      template: answers.html.twig

            form:
                fields:
                    - property: title
                    - property: description
                      type: ckeditor
                    - property: instructions
                      type: ckeditor
                    - property: configuration
                      type: AppBundle\Form\Type\ConfigurationType
                    - property: questions
                      type: collection
                      type_options:
                        entry_type: AppBundle\Form\Type\QuestionType
                        by_reference: false
                        required: true
                      embedded: true

        Answer:
            class: AppBundle\Entity\Answer
            disabled_actions: [edit, delete]
            list:
                actions:
                    - name: answer_show
                      type: route
                      label: action.show
                    - name: answer_edit
                      type: route
                      label: action.edit
                fields:
                    - property: survey
                    - property: title
                    - property: survey
                    - property: author
                    - property: description
                    - property: createdAt

        User:
            class: Itk\Bundle\EasyAdminUserBundle\Entity\User
            list:
                fields:
                    - property: email
                    - property: roles
                    - property: last_login
                      type: datetime

            form:
                fields:
                    - property: email
                      type: email
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices: &role_list
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN
