services:
    Itk\Bundle\EasyAdminUserBundle\Twig\AdminUserExtension:
        arguments:
            - '@service_container'
        tags: [ twig.extension ]

    Itk\Bundle\EasyAdminUserBundle\Service\UserManager:
        arguments:
            - '@fos_user.util.password_updater'
            - '@fos_user.util.canonical_fields_updater'
            - '@fos_user.object_manager'
            - '%fos_user.model.user.class%'
            - '@fos_user.util.token_generator'
            - '@twig'
            - '@router'
            - '@mailer'
            -
                sender:
                    email: '%mailer_email%'
                    name: '%mailer_name%'
                user_created: '%user_created%'
